# QtClass Config
name: programming-with-python
version: 0.2.1
title: Python编程教程
author: 量潮课堂
description: Python语言和编程入门到进阶
level: introductory
stage: dev
tags:
  - python
# Jupyter Book Config
only_build_toc_files: true